### ISSUE TITLE
ES Support + Clean Env

### ISSUE THREAD

**Issue by atrope** [whilenull/7777-support#10]
Hi @mnapoli,
First of all i'd like to say that this is a great idea and a marvelous job!
Everything worked like a charm as it should and after my tests(I bought the individual license) i will buy the team license for our devs.
I Have some questions regarding the future of 7777

1 - Will you support more AWS services like ES for example? Today we have a Bastion configured on AWS only to use ES + DB

2 - Can we maybe support Aurora/RDS Clusters? Because today i can only choose the reader/writer not both.

3 - What would happen if I turn off the PC without closing the service, or if the service gets killed(if I Start in the background so i dont need the open terminal), i will need to manually remove the stack right? Can we have the option of maybe "7777 clean"? Or some time-based(?) cron that will set the max time it will auto delete the bastion?

Guess that's all, again great job for all the team!

**Comment by deleugpn** [comment]
Hi @atrope, thank you for your feedback and for buying port7777! I will answer your questions in reverse order.

> 3 - What would happen if I turn off the PC without closing the service, or if the service gets killed(if I Start in the background so i dont need the open terminal), i will need to manually remove the stack right? Can we have the option of maybe "7777 clean"? Or some time-based(?) cron that will set the max time it will auto delete the bastion?

By default, your tunnel runs for 2 hours and automatically shuts down after that period. You can [increase the time](https://github.com/whilenull/7777-support/blob/main/commands.md#--ttl) using `--ttl 24` for 24 hours, for instance. You can also [list all running containers](https://github.com/whilenull/7777-support/blob/main/commands.md#7777-list) with `7777 list` and [stop a specific container](https://github.com/whilenull/7777-support/blob/main/commands.md#7777-stop) with `7777 stop --task YOUR_ARN_TASK`.

> 2 - Can we maybe support Aurora/RDS Clusters? Because today i can only choose the reader/writer not both.

We do support Clusters, but only for Serverless instances. The reason for that is because your local port can only establish a single connection to a single endpoint. If we were to allow you to select a cluster, what would it be your expected outcome?

> 1 - Will you support more AWS services like ES for example? Today we have a Bastion configured on AWS only to use ES + DB

Right now I'm working on a possible support for Redis (Elasticache) and we may consider Elasticsearch afterwards if we manage to successfully launch Redis.

**Comment by mnapoli** [comment]
> By default, your tunnel runs for 2 hours and automatically shuts down after that period.

And to add on that, the timeout runs in the Fargate container. If the connection drops entirely the container will self-terminate.

**Comment by deleugpn** [comment]
> 3 - Perfect! It will list all my team(Account) running tasks or only mine? does ttl support decimal? or 1 is the minimum?

You will get all tasks running on the 7777Cluster regardless of who started it.

> 2 - In My app i have "Read Endpoints" and "Write Endpoints", the outcome would be to be able to have 2 "local endpoints" so in my app i can setup them both and the app will work just like it works on our Prod/Stage env.

We wouldn't be able to support this without using 2 separate ports. Maybe **localhost:7777** would be read instance and **localhost:7778** would be your write instance. You can still achieve that, but you'll have to run 7777 twice. Currently we haven't planned anything to make this automatic.

**Comment by atrope** [comment]
Perfect, that's what I thought on running it twice( or thrice when ES is supported :) )

Will be closing the issue as all my questions were answered.


Thanks!
