### ISSUE TITLE
Connections timing out after a few minutes.

### ISSUE THREAD

**Issue by BenCoffeed** [whilenull/7777-support#30]
I have a user reporting an issue where 7777 is disconnecting after a few minutes if he takes a phone call or steps away from his computer. The time ranges appear to be far lower than the 2 hour default TTL. Are there any known issues with MacOS features such as app nap or disk sleep that will cause the connection to die?

**Comment by deleugpn** [comment]
Hey there, sorry for the long response time. What you described here does seem likely to cause issues because if your operating system goes into suspension mode, the TCP connection might get affected and closed down. If you use `--verbose` on 7777 and the computer causes a disk sleep, maybe you might be able to see the information of 7777 shutting down once the computer is woken up?

**Comment by mnapoli** [comment]
FYI I published a new version of 7777 with built-in "keep-alive" for SSH connexions. This should help make the connection/tunnel more stable.

I'll be closing this since it's more than a year old and a fix is out. Let us know if you have issues still.
