### ISSUE TITLE
Unable to negotiate with <ip> port 64764: no matching host key type found.

### ISSUE THREAD

**Issue by slootjes** [whilenull/7777-support#45]
Running 7777 in Docker, only version I can find is "port7777/7777:1" and it started giving this error:

Unable to negotiate with <my ip> port 64764: no matching host key type found. Their offer: ssh-ed25519,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521,ssh-rsa [preauth]

Container shuts down, 7777 client doesn't show any sign of error.

When running the container it also shows this warning on startup:

```
| A new version (1.1.12) of 7777 is available: you are currently running version 1.1.4.
| To update follow this guide: https://github.com/whilenull/7777-support/blob/main/README.md#installation-and-update
```
It would be great if the latest version can be made available to Docker users (preferably automatically and possibility to use "port7777/7777:latest).

**Comment by mnapoli** [comment]
Hi,

I just tried and had the latest version, no issue.

Could you try pull the latest version of the Docker image?

```
docker pull port7777/7777:1
```

**Comment by slootjes** [comment]
This seems to work, thank you. Could it perhaps be documented that it's required to manually pull versions when a new version of 7777 is released? Preferably the version of 7777 is reflected in the version of the container.

**Comment by mnapoli** [comment]
Great! It isn't really required to pull a new version, unless you encounter a bug.

Docker is mostly used in CI anyway, so the latest version will be used anyway (because most CI systems have an empty cache). When used outside of Docker, the CLI shows that an old version is used, so users can update (just like they would update any Docker image).

Closing since this is fixed 🙌
